### ISSUE TITLE
Define definition of done

### ISSUE THREAD

**Issue by mrmetaverse** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#17]

**Comment by bwingerd** [comment]
1.  Acceptance criteria met
2.  For code: PR completed
                      Code integrated into main with no testing errors 
4. For content/documentation/customer engagement:  Product Owner/CMS review and approval
5. Meets compliance requirements, if applicable
6. Functionality documented in user documentation, if applicable
