### ISSUE TITLE
Push AWS branch up to github

### ISSUE THREAD

**Issue by mrmetaverse** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#24]
Push AWS branch up to github (new ticket)

![image](https://user-images.githubusercontent.com/63426722/184430009-44f3dc81-8685-4d44-8d74-8c5d792ff9de.png)

_Originally posted by @mrmetaverse in https://github.com/FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API/issues/23#issuecomment-1213420126_

**Comment by mrmetaverse** [comment]
related to #23

**Comment by mrmetaverse** [comment]
![image](https://user-images.githubusercontent.com/63426722/184447356-261015ba-3be1-44e1-bae4-54a9a551ce0d.png)

Moving to "review" for @sharshar-sb to approve 

cc: @jarod-rosenthal

**Comment by sharshar-sb** [comment]
@jarod-rosenthal Go ahead and create a pull request to merge it in to main. As everything is a prototype, I'm less worried about checking everything into main ASAP.
