### ISSUE TITLE
Auth: Implement Okta endpoint

### ISSUE THREAD

**Issue by bwingerd** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#25]

**Comment by sharshar-sb** [comment]
Works to create a token with the following information:

https://dev-91595043.okta.com/oauth2/aus669kv6e0Mcbkww5d7/v1/token?grant_type=client_credentials&scope=clientCreds

For authorization, use basic with the client id and password found in:
https://dev-91595043-admin.okta.com/admin/app/oidc_client/instance/0oa65gvwspD62HC1m5d7/#tab-general
