### ISSUE TITLE
Establish a product vision and strategy

### ISSUE THREAD

**Issue by mrmetaverse** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#3]
My Final Draft for review: 

**Vision: A secure way to intuitively and reliably send and review VA Patient and Coverage data in bulk to CMS.**

This is [still a work in progress](https://github.com/FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API/issues/3) :point_up:, and references what CMS defines as the ideal future state in the README.

>CMS envisions a minimum viable product that allows the VA to send Patient and Coverage data to CMS in bulk, and CMS users to query the Patient and Coverage data individually.

**Comment by mrmetaverse** [comment]
As you will find in our [README](https://github.com/FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#tags-fearless-bcda) links at the top, I have created a [Veteran Attribution API PRD](https://hackmd.io/@mrmetaverse/b2d2-tech-challenge-PRD) for tracking some of the high level product stuff for this project. Most relevant to this ticket, I created a draft vision placeholder, using their own language from the README. 

## draft Vision: A secure way to intuitively and reliably send VA Patient and Coverage data to CMS in bulk. 

>From the quote: 
_CMS envisions a minimum viable product that allows the VA to send Patient and Coverage data to CMS in bulk._

**Comment by mrmetaverse** [comment]
My Final Draft for review: 

**Vision: A secure way to intuitively and reliably send and review VA Patient and Coverage data in bulk to CMS.**

This is [still a work in progress](https://github.com/FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API/issues/3) :point_up:, and references what CMS defines as the ideal future state in the README.

>CMS envisions a minimum viable product that allows the VA to send Patient and Coverage data to CMS in bulk, and CMS users to query the Patient and Coverage data individually.

**Comment by bwingerd** [comment]
Suggest we modify "in bulk and individually" since they mention both in the RFP.

**Comment by bwingerd** [comment]
Is it only CMS Users that are going to query the data?  Or is it both CMS customers and VA users?

**Comment by mrmetaverse** [comment]
> Is it only CMS Users that are going to query the data? Or is it both CMS customers and VA users?

@sharshar-sb have an answer?

**Comment by mrmetaverse** [comment]
I actually think we can remove in bulk and individually. 

Vision: A secure way to intuitively and reliably send and review VA Patient and Coverage data to CMS
