### ISSUE TITLE
Create a product roadmap

### ISSUE THREAD

**Issue by mrmetaverse** [FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API#6]
We can create a [theme based high-level roadmap](https://www.figma.com/file/43ocI355P9YXsvVwy2Mowd/Veteran-Attribution-API---Tech-Challenge-08%2F2022?node-id=201%3A2) as we have done before with BCDA and DPC. We would need more information, and more time to create a fully detailed roadmap. Themes are in scope, and what matters most for alignment anyways. I used a [template I created years ago]((https://www.figma.com/community/file/971447908536638281) and use often.

**Comment by mrmetaverse** [comment]
What if we use the #2 Success criteria defined to help create our [Thematic Roadmap](https://www.figma.com/community/file/971447908536638281)? 

**Themes:**
- Technical Solution 
- Product Delivery 
- HCD 
- Data Management 
- Additional Elements 


And add any others we know are missing: 
- Users and Permissions 
- Automation and Testing 
- etc.

**Comment by mrmetaverse** [comment]
Team will create themes of work to "own" and get them to me, I will use to create early thematic roadmap.

**Comment by mrmetaverse** [comment]
List made available in #2

**Comment by mrmetaverse** [comment]
Draft: 

![image](https://user-images.githubusercontent.com/63426722/184246734-a549947d-088a-4d18-8ad0-5c83cb7cd5f5.png)

https://www.figma.com/file/43ocI355P9YXsvVwy2Mowd/Theme-Based-Product-Roadmap-(Community)?node-id=0%3A1

**Comment by mrmetaverse** [comment]
From todays https://github.com/FearlessSolutions/BCDA-DPC-B2D2-Veteran-Attribution-API/discussions/16 standup notes
####  Tactical roadmap 
* **by end of Today:** Every theme has an assigned lead, Every theme has high level goals and milestones, AWS by today 
* **by end of Monday**: MVP definition (sort thematic roadmap), 
* **by end of Tuesday:** Technical architecture draft by Tuesday, dev OKTA by Tuesday 
* **by the end of Wednesday:** Gain feedback, comments about technical architecture. Defined languages to use (java, go, etc.)
* **by end of Thursday:** containers would be nice to have by Thursday :rotating_light: NEED TO HAVE DEV DONE BY THURSDAY 
* **by the end of Friday:** hope most of this is in AWS, if we go with fargate we have fargate task definitions ready to accept whatever language

**Comment by bwingerd** [comment]
Love the way this is structured!

**Comment by mrmetaverse** [comment]
Draft Ready for Review! 


![Image](https://user-images.githubusercontent.com/63426722/184649397-62a610a5-4528-4945-842d-c6b7f26a1c14.png)

**Comment by mrmetaverse** [comment]
Team reviewed in our meeting today, and will continue to review today to ensure each theme of goals are aligned with our intentions, and that the defined milestones for each goal reflect (to the best of our ability) the work that remains. 

I will also add the #3 Vision to the roadmap
